/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    kotlin("jvm") version "2.0.20"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("http://repository.jboss.org/maven2")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("http://repository.springsource.com/maven/bundles/release")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("http://repository.springsource.com/maven/bundles/external")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("http://repository.springsource.com/maven/bundles/milestone")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("http://repository.springsource.com/maven/bundles/snapshot")

        // isAllowInsecureProtocol = true
    }

    maven {
        url = uri("http://oss.sonatype.org/content/repositories/sourceforge-releases/net/sf/ehcache/")

        // isAllowInsecureProtocol = true
    }
}

dependencies {
    implementation(kotlin("stdlib"))
    api(libs.log4j.log4j)
    api(libs.org.apache.commons.commons.lang3)
    api(libs.javax.validation.validation.api)
    api(libs.javax.transaction.transaction.api)
    api(libs.com.mysql.jdbc.com.springsource.com.mysql.jdbc)
    api(libs.org.hibernate.hibernate.core)
    api(libs.org.hibernate.hibernate.entitymanager)
    api(libs.org.hibernate.hibernate.validator)
    api(libs.org.hibernate.javax.persistence.hibernate.jpa.v2.v0.api)
    api(libs.org.aspectj.aspectjweaver)
    api(libs.org.aspectj.aspectjrt)
    api(libs.net.sf.ehcache.ehcache.core)
    api(libs.org.springframework.org.springframework.core)
    api(libs.org.springframework.org.springframework.transaction)
    api(libs.org.springframework.org.springframework.web)
    api(libs.org.springframework.org.springframework.web.servlet)
    api(libs.org.springframework.org.springframework.orm)
    api(libs.org.springframework.org.springframework.aspects)
    api(libs.org.springframework.org.springframework.oxm)
    api(libs.org.springframework.webflow.org.springframework.js)
    api(libs.org.springframework.security.org.springframework.security.core)
    api(libs.org.springframework.security.org.springframework.security.config)
    api(libs.org.springframework.security.org.springframework.security.web)
    api(libs.org.springframework.security.org.springframework.security.taglibs)
    api(libs.org.springframework.security.org.springframework.security.openid)
    api(libs.javax.servlet.com.springsource.javax.servlet.jsp.jstl)
    api(libs.org.apache.commons.com.springsource.org.apache.commons.fileupload)
    testImplementation(libs.org.springframework.org.springframework.test)
    providedCompile(libs.commons.logging.commons.logging)
    providedCompile(libs.javax.servlet.com.springsource.javax.servlet)
}

group = "com.retailwave.fce"
version = "0.0.1-SNAPSHOT"
description = "Finance Costing Engine"
java.sourceCompatibility = JavaVersion.VERSION_1_6

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
