package intellibitz.intellidroid.widget.advrecyclerview.swipeable

interface SwipeableItemConstants {
    companion object {
        const val STATE_FLAG_SWIPING = 1 shl 0
        const val STATE_FLAG_IS_ACTIVE = 1 shl 1
        const val STATE_FLAG_IS_UPDATED = 1 shl 31

        const val RESULT_NONE = 0
        const val RESULT_CANCELED = 1
        const val RESULT_SWIPED_LEFT = 2
        const val RESULT_SWIPED_UP = 3
        const val RESULT_SWIPED_RIGHT = 4
        const val RESULT_SWIPED_DOWN = 5

        const val REACTION_CAN_NOT_SWIPE_ANY = 0
        const val REACTION_CAN_NOT_SWIPE_LEFT = InternalConstants.REACTION_CAN_NOT_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_LEFT
        const val REACTION_CAN_NOT_SWIPE_LEFT_WITH_RUBBER_BAND_EFFECT = InternalConstants.REACTION_CAN_NOT_SWIPE_WITH_RUBBER_BAND_EFFECT shl InternalConstants.BIT_SHIFT_AMOUNT_LEFT
        const val REACTION_CAN_SWIPE_LEFT = InternalConstants.REACTION_CAN_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_LEFT
        const val REACTION_MASK_START_SWIPE_LEFT = InternalConstants.REACTION_MASK_START_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_LEFT

        const val REACTION_CAN_NOT_SWIPE_UP = InternalConstants.REACTION_CAN_NOT_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_UP
        const val REACTION_CAN_NOT_SWIPE_UP_WITH_RUBBER_BAND_EFFECT = InternalConstants.REACTION_CAN_NOT_SWIPE_WITH_RUBBER_BAND_EFFECT shl InternalConstants.BIT_SHIFT_AMOUNT_UP
        const val REACTION_CAN_SWIPE_UP = InternalConstants.REACTION_CAN_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_UP
        const val REACTION_MASK_START_SWIPE_UP = InternalConstants.REACTION_MASK_START_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_UP

        const val REACTION_CAN_NOT_SWIPE_RIGHT = InternalConstants.REACTION_CAN_NOT_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_RIGHT
        const val REACTION_CAN_NOT_SWIPE_RIGHT_WITH_RUBBER_BAND_EFFECT = InternalConstants.REACTION_CAN_NOT_SWIPE_WITH_RUBBER_BAND_EFFECT shl InternalConstants.BIT_SHIFT_AMOUNT_RIGHT
        const val REACTION_CAN_SWIPE_RIGHT = InternalConstants.REACTION_CAN_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_RIGHT
        const val REACTION_MASK_START_SWIPE_RIGHT = InternalConstants.REACTION_MASK_START_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_RIGHT

        const val REACTION_CAN_NOT_SWIPE_DOWN = InternalConstants.REACTION_CAN_NOT_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_DOWN
        const val REACTION_CAN_NOT_SWIPE_DOWN_WITH_RUBBER_BAND_EFFECT = InternalConstants.REACTION_CAN_NOT_SWIPE_WITH_RUBBER_BAND_EFFECT shl InternalConstants.BIT_SHIFT_AMOUNT_DOWN
        const val REACTION_CAN_SWIPE_DOWN = InternalConstants.REACTION_CAN_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_DOWN
        const val REACTION_MASK_START_SWIPE_DOWN = InternalConstants.REACTION_MASK_START_SWIPE shl InternalConstants.BIT_SHIFT_AMOUNT_DOWN

        const val REACTION_START_SWIPE_ON_LONG_PRESS = InternalConstants.REACTION_START_SWIPE_ON_LONG_PRESS

        const val REACTION_CAN_NOT_SWIPE_BOTH_H = REACTION_CAN_NOT_SWIPE_LEFT or REACTION_CAN_NOT_SWIPE_RIGHT
        const val REACTION_CAN_NOT_SWIPE_BOTH_H_WITH_RUBBER_BAND_EFFECT = REACTION_CAN_NOT_SWIPE_LEFT_WITH_RUBBER_BAND_EFFECT or REACTION_CAN_NOT_SWIPE_RIGHT_WITH_RUBBER_BAND_EFFECT
        const val REACTION_CAN_SWIPE_BOTH_H = REACTION_CAN_SWIPE_LEFT or REACTION_CAN_SWIPE_RIGHT

        const val REACTION_CAN_NOT_SWIPE_BOTH_V = REACTION_CAN_NOT_SWIPE_UP or REACTION_CAN_NOT_SWIPE_DOWN
        const val REACTION_CAN_NOT_SWIPE_BOTH_V_WITH_RUBBER_BAND_EFFECT = REACTION_CAN_NOT_SWIPE_UP_WITH_RUBBER_BAND_EFFECT or REACTION_CAN_NOT_SWIPE_DOWN_WITH_RUBBER_BAND_EFFECT
        const val REACTION_CAN_SWIPE_BOTH_V = REACTION_CAN_SWIPE_UP or REACTION_CAN_SWIPE_DOWN

        @Deprecated("Use REACTION_CAN_NOT_SWIPE_ANY directly.")
        const val REACTION_CAN_NOT_SWIPE_BOTH = REACTION_CAN_NOT_SWIPE_ANY

        @Deprecated("Use REACTION_CAN_NOT_SWIPE_BOTH_H_WITH_RUBBER_BAND_EFFECT directly.")
        const val REACTION_CAN_NOT_SWIPE_BOTH_WITH_RUBBER_BAND_EFFECT = REACTION_CAN_NOT_SWIPE_BOTH_H_WITH_RUBBER_BAND_EFFECT

        @Deprecated("Use REACTION_CAN_SWIPE_BOTH_H directly.")
        const val REACTION_CAN_SWIPE_BOTH = REACTION_CAN_SWIPE_BOTH_H

        const val DRAWABLE_SWIPE_NEUTRAL_BACKGROUND = 0
        const val DRAWABLE_SWIPE_LEFT_BACKGROUND = 1
        const val DRAWABLE_SWIPE_UP_BACKGROUND = 2
        const val DRAWABLE_SWIPE_RIGHT_BACKGROUND = 3
        const val DRAWABLE_SWIPE_DOWN_BACKGROUND = 4

        const val AFTER_SWIPE_REACTION_DEFAULT = 0
        const val AFTER_SWIPE_REACTION_REMOVE_ITEM = 1
        const val AFTER_SWIPE_REACTION_MOVE_TO_SWIPED_DIRECTION = 2

        const val OUTSIDE_OF_THE_WINDOW_LEFT = -((1 shl 16) + 0).toFloat()
        const val OUTSIDE_OF_THE_WINDOW_TOP = -((1 shl 16) + 1).toFloat()
        const val OUTSIDE_OF_THE_WINDOW_RIGHT = ((1 shl 16) + 0).toFloat()
        const val OUTSIDE_OF_THE_WINDOW_BOTTOM = ((1 shl 16) + 1).toFloat()
    }
}
