package intellibitz.intellidroid.db

interface IntellibitzItemColumns {
    companion object {
        const val KEY_ID = "_id"
        const val KEY_DATA_ID = "id"
        const val KEY_THREAD_ID = "thread_id"
        const val KEY_THREAD_IDREF = "thread_idref"
        const val KEY_THREAD_IDPARTS = "thread_idparts"
        const val KEY_GROUP_ID = "group_id"
        const val KEY_GROUP_IDREF = "group_idref"
        const val KEY_TYPE_ID = "type_id"
        const val KEY_DATA_REV = "_rev"
        const val KEY_INTELLIBITZ_ID = "intellibitz_id"
        const val KEY_IS_GROUP = "is_group"
        const val KEY_IS_EMAIL = "is_email"
        const val KEY_IS_ANONYMOUS = "is_anonymous"
        const val KEY_IS_DEVICE = "is_device"
        const val KEY_IS_CLOUD = "is_cloud"
        const val KEY_FIRST_NAME = "first_name"
        const val KEY_LAST_NAME = "last_name"
        const val KEY_DISPLAY_NAME = "display_name"
        const val KEY_DEVICE_CONTACTID = "contact_id"
        const val KEY_DOC_TYPE = "doc_type"
        const val KEY_BASE_TYPE = "base_type"
        const val KEY_TYPE = "type"
        const val KEY_NAME = "name"
        const val KEY_PIC = "profile_pic"
        const val KEY_CLOUD_PIC = "cloud_pic"
        const val KEY_COMPANY_ID = "company_id"
        const val KEY_COMPANY_NAME = "company_name"
        const val KEY_EMAIL = "email"
        const val KEY_EMAIL_CODE = "email_code"
        const val KEY_ACTIVE = "active"
        const val KEY_DEVICE_ID = "device_id"
        const val KEY_DEVICE_NAME = "device_name"
        const val KEY_DEVICE_REF = "device_ref"
        const val KEY_DOC_OWNER = "doc_owner"
        const val KEY_STATUS = "status"
        const val KEY_REF_ID = "ref_id"
        const val KEY_TIMESTAMP = "timestamp"
        const val KEY_DATETIME = "datetime"

        const val TABLE_INFOS_SCHEMA = ("( "
                + KEY_ID + " INTEGER PRIMARY KEY,"
                + KEY_DATA_ID + " TEXT,"
                + KEY_REF_ID + " TEXT,"
                + KEY_DATA_REV + " TEXT,"
                + KEY_TYPE + " TEXT,"
                + KEY_DEVICE_REF + " TEXT,"
                + KEY_DOC_OWNER + " TEXT,"
                + KEY_DOC_TYPE + " TEXT,"
                + KEY_NAME + " TEXT,"
                + KEY_PIC + " TEXT,"
                + KEY_TIMESTAMP + " LONG,"
                + KEY_DATETIME + " DATETIME" + ")")
        const val TABLE_INFOS = "infos"
        const val CREATE_TABLE_INFOS = "CREATE TABLE " + TABLE_INFOS + TABLE_INFOS_SCHEMA
    }
}
