/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "intellidocs"
include(":intellidocs-ear")
include(":user-guide")
include(":intellidocs-ejb")
include(":intellidocs-war")
