/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    war
}

dependencies {
    api(libs.org.jboss.seam.jboss.seam.debug) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-beanutils", "module" to "commons-beanutils"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-collections", "module" to "commons-collections"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-digester", "module" to "commons-digester"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet.jsp", "module" to "jsp-api"))
    }
    api(libs.org.jboss.seam.jboss.seam.ui) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-beanutils", "module" to "commons-beanutils"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-collections", "module" to "commons-collections"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-digester", "module" to "commons-digester"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet.jsp", "module" to "jsp-api"))
    }
    api(libs.org.richfaces.framework.richfaces.api) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-beanutils", "module" to "commons-beanutils"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-collections", "module" to "commons-collections"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-digester", "module" to "commons-digester"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "junit", "module" to "junit"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-impl"))
    }
    api(libs.org.richfaces.framework.richfaces.impl) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-beanutils", "module" to "commons-beanutils"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-collections", "module" to "commons-collections"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-digester", "module" to "commons-digester"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "junit", "module" to "junit"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-impl"))
    }
    api(libs.org.richfaces.ui.richfaces.ui) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-beanutils", "module" to "commons-beanutils"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-collections", "module" to "commons-collections"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-digester", "module" to "commons-digester"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.faces", "module" to "jsf-impl"))
    }
    api(libs.com.sun.facelets.jsf.facelets)
    providedCompile(project(":intellidocs-ejb"))
    providedCompile(libs.org.jboss.seam.jboss.seam) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet.jsp", "module" to "jsp-api"))
    }
    providedCompile(libs.org.jboss.seam.jboss.el)
    providedCompile(libs.javax.transaction.jta)
    providedCompile(libs.javax.servlet.servlet.api)
    providedCompile(libs.javax.servlet.jsp.api)
    providedCompile(libs.org.jboss.embedded.hibernate.all)
    providedCompile(libs.org.jboss.embedded.jboss.embedded.all)
    providedCompile(libs.org.jboss.embedded.thirdparty.all)
    providedCompile(libs.org.jboss.embedded.jboss.deployers)
    providedCompile(libs.javax.ejb.ejb.api)
    providedCompile(libs.javax.persistence.persistence.api)
    providedCompile(libs.org.hibernate.hibernate.validator)
    providedCompile(libs.org.hibernate.hibernate.annotations.x1) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "junit", "module" to "junit"))
    }
    providedCompile(libs.org.hibernate.hibernate.commons.annotations)
    providedCompile(libs.postgresql.postgresql)
    providedCompile(libs.javax.el.el.api)
    providedCompile(libs.javax.faces.jsf.api)
    providedCompile(libs.javax.faces.jsf.impl)
}

description = "intellidocs-war"

tasks.named<Jar>("jar") {
    isEnabled = true
}
