/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("http://ns3:8081/artifactory/repo")

        // isAllowInsecureProtocol = true
    }
}

dependencies {
    api(libs.com.ibt.intellimeet.intellimeet.ejb)
    api(libs.com.ibt.intellimeet.intellimeet.war.tests)
    api(libs.org.jboss.seam.jboss.seam) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
    api(libs.org.jboss.seam.jboss.el) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
    api(libs.commons.digester.commons.digester) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.testng.testng)
    testImplementation(libs.junit.junit)
    testImplementation(libs.org.testng.testng)
    compileOnly(libs.groovy.groovy.all)
    compileOnly(libs.groovy.groovy.all)
}

group = "com.ibt.intellimeet"
version = "1.0-SNAPSHOT"
description = "intellimeet-ear-tests"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG()
}
