/*
 * This source file was generated by the Gradle 'init' task
 */
package org.app

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test

class AppTest {
    @Test
    fun appHasAGreeting() {
        val classUnderTest = App()
        assertNotNull("app should have a greeting", classUnderTest.getGreeting())
    }
}
