/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "intellimeet"
include(":intellimeet-ear")
include(":intellimeet-war")
include(":user-guide")
include(":intellimeet-ejb")
