package intellibitz.intellidroid.widget.advrecyclerview.swipeable.action

import intellibitz.intellidroid.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager

open class SwipeResultActionDefault : SwipeResultAction(RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_DEFAULT)
