package intellibitz.intellidroid.widget.advrecyclerview.swipeable.action

import intellibitz.intellidroid.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager

abstract class SwipeResultActionRemoveItem :
    SwipeResultAction(RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_REMOVE_ITEM)
