/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":intellimeet-ejb"))
    api(project(":intellimeet-war"))
    api(libs.org.jboss.seam.jboss.seam) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
    api(libs.org.jboss.seam.jboss.el) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
    api(libs.commons.digester.commons.digester) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))
    }
}

description = "intellimeet-ear"
