package intellibitz.intellidroid.widget.advrecyclerview.swipeable.action

import intellibitz.intellidroid.widget.advrecyclerview.swipeable.RecyclerViewSwipeManager

abstract class SwipeResultActionMoveToSwipedDirection :
    SwipeResultAction(RecyclerViewSwipeManager.AFTER_SWIPE_REACTION_MOVE_TO_SWIPED_DIRECTION)
