/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    compileOnly(libs.org.jboss.embedded.hibernate.all)
    compileOnly(libs.org.jboss.embedded.jboss.embedded.all)
    compileOnly(libs.org.jboss.embedded.thirdparty.all)
    compileOnly(libs.org.jboss.embedded.jboss.deployers)
    compileOnly(libs.javax.ejb.ejb.api)
    compileOnly(libs.javax.persistence.persistence.api)
    compileOnly(libs.org.jboss.seam.jboss.seam) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "dom4j", "module" to "dom4j"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jboss", "module" to "javassist"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.el", "module" to "el-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet", "module" to "servlet-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.servlet.jsp", "module" to "jsp-api"))
    }
    compileOnly(libs.org.hibernate.hibernate.validator)
    compileOnly(libs.org.hibernate.hibernate.annotations) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.7.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "junit", "module" to "junit"))
    }
    compileOnly(libs.org.hibernate.hibernate.commons.annotations)
    compileOnly(libs.postgresql.postgresql)
    compileOnly(libs.javax.servlet.servlet.api)
    compileOnly(libs.javax.servlet.jsp.api)
    compileOnly(libs.javax.el.el.api)
    compileOnly(libs.javax.faces.jsf.api)
    compileOnly(libs.javax.faces.jsf.impl)
}

description = "intellidocs-ejb"
