/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("http://ns3:8081/artifactory/repo")

        // isAllowInsecureProtocol = true
    }
}

dependencies {
    testImplementation("junit:junit:4.0")
    testImplementation("org.testng:testng:5.1")
}

group = "com.ibt.intellidocs"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.named<Test>("test") {
    useTestNG()
}
