/*
 * This source file was generated by the Gradle 'init' task
 */
package org.app

class App {
    fun getGreeting(): String {
        return "Hello World!"
    }

    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            println(App().getGreeting())
        }
    }
}
